### ISSUE TITLE
请问一下模型数据的输入维度是多少？

### ISSUE THREAD

**Issue by JohnnyQAQ** [pengjuRen99/ViT_1D_RamanSpectra_Classification#1]
我目前数据集维度是（-1，500），按照下图设置参数的话会显示要求输入3D数据，在增加1维通道数之后又会说1无法被patch_size所整除，所以想问一下您这边数据的维度是多少？
![image](https://github.com/pengjuRen99/ViT_1D_RamanSpectra_Classification/assets/33392484/e7c15aae-6a24-4e25-bae7-4e7f812ee5a4)

**Comment by pengjuRen99** [comment]
我的数据集维度是(1, 1400)，实际要求输入数据为对应着(batch_size, 1, 1400)，第一个维度为批量大小，并不是代表着3D数据。patch_size的大小，由于self-attention关系，所以要将光谱分块处理，要与你输入的数据维度是整除的关系，在这里我的维度是1400，所以只能设置能将1400整除的数字。或者不整除可以将最后一个块用0进行填充。
